export const ORDERID = "orderId";
export const USEREMAIL = "userEmail";
export const USERFIRSTNAME = "userFirstName";
export const USERLASTNAME = "userLastName";
export const USERCOUNTY = "userCounty";
export const USERCITY = "userCity";
export const USERADDRESS = "userAddress";
export const TOTALPRICE = "totalPrice";
export const SHIPPINGSTATUS = "shippingStatus";

export const ORDERID_LABEL = "Order ID";
export const USEREMAIL_LABEL = "User email";
export const USERFIRSTNAME_LABEL = "User first name";
export const USERLASTNAME_LABEL = "User last name";
export const USERCOUNTY_LABEL = "User county";
export const USERCITY_LABEL = "User city";
export const USERADDRESS_LABEL = "User address";
export const TOTALPRICE_LABEL = "Total price";
export const SHIPPINGSTATUS_LABEL = "Shipping status";
