export const COMPONENTID = "componentId";
export const MAKE = "make";
export const MODEL = "model";
export const PRICE = "price";
export const IMAGE = "image";
export const TYPE = "type";
export const CAPACITY = "capacity";
export const FREQUENCY = "frequency";
export const VOLTAGE = "voltage";

export const COMPONENTID_LABEL = "Component ID";
export const MAKE_LABEL = "Make";
export const MODEL_LABEL = "Model";
export const PRICE_LABEL = "Price";
export const IMAGE_LABEL = "Image";
export const TYPE_LABEL = "Type";
export const CAPACITY_LABEL = "Capacity";
export const FREQUENCY_LABEL = "Frequency";
export const VOLTAGE_LABEL = "Voltage";
