export const USERID = "userId";
export const FIRST_NAME = "firstName";
export const LAST_NAME = "lastName";
export const EMAIL = "email";
export const PASSWORD = "password";
export const CITY = "city";
export const COUNTY = "county";
export const ADDRESS = "address";
export const ADMIN = "admin";

export const USERID_LABEL = "User ID";
export const FIRST_NAME_LABEL = "First Name";
export const LAST_NAME_LABEL = "Last Name";
export const EMAIL_LABEL = "Email";
export const PASSWORD_LABEL = "Password";
export const CITY_LABEL = "City";
export const COUNTY_LABEL = "County";
export const ADDRESS_LABEL = "Address";
export const ADMIN_LABEL = "Admin";
